### ISSUE TITLE
Invalid JSON appears to be uploaded

### ISSUE THREAD

**Issue by abbyad** [alxndrsn/medic-configurer#7]
If you upload invalid JSON for the app_settings the destination is thankfully not updated, however there is no notice of such in the command line:

```
medic-conf . https://admin:[password]@[instance].app.medicmobile.org upload-app-settings
INFO Processing config in . for https://admin:****@standard.app.medicmobile.org.
INFO Actions:
     - upload-app-settings
INFO Extra args: undefined
INFO Starting action: upload-app-settings…
INFO upload-app-settings complete.
```

The actual response when uploading invalid JSON is: `{"error":"bad_request","reason":"invalid_json"}`
We should report this back to the user.

**Comment by alxndrsn** [comment]
FIXED

**Comment by abbyad** [comment]
Works well!
